import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { ToolBar } from "./_components/toolbar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={clsx("min-h-screen", "dark:bg-zinc-900")}>
                {/* <ToolBar /> */}
                {children}
            </body>
        </html>
    );
}
